// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewNoteAdder creates a new instance of NoteAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteAdder {
	mock := &NoteAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NoteAdder is an autogenerated mock type for the NoteAdder type
type NoteAdder struct {
	mock.Mock
}

type NoteAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *NoteAdder) EXPECT() *NoteAdder_Expecter {
	return &NoteAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type NoteAdder
func (_mock *NoteAdder) Add(title string, text string) error {
	ret := _mock.Called(title, text)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(title, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NoteAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type NoteAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - title string
//   - text string
func (_e *NoteAdder_Expecter) Add(title interface{}, text interface{}) *NoteAdder_Add_Call {
	return &NoteAdder_Add_Call{Call: _e.mock.On("Add", title, text)}
}

func (_c *NoteAdder_Add_Call) Run(run func(title string, text string)) *NoteAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NoteAdder_Add_Call) Return(err error) *NoteAdder_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NoteAdder_Add_Call) RunAndReturn(run func(title string, text string) error) *NoteAdder_Add_Call {
	_c.Call.Return(run)
	return _c
}
