// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"protomorphine/tg-notes/internal/domain"
)

// NewClassifier creates a new instance of Classifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Classifier {
	mock := &Classifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Classifier is an autogenerated mock type for the Classifier type
type Classifier struct {
	mock.Mock
}

type Classifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Classifier) EXPECT() *Classifier_Expecter {
	return &Classifier_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function for the type Classifier
func (_mock *Classifier) Classify(content string) (map[domain.Category]float64, domain.Category) {
	ret := _mock.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 map[domain.Category]float64
	var r1 domain.Category
	if returnFunc, ok := ret.Get(0).(func(string) (map[domain.Category]float64, domain.Category)); ok {
		return returnFunc(content)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[domain.Category]float64); ok {
		r0 = returnFunc(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[domain.Category]float64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) domain.Category); ok {
		r1 = returnFunc(content)
	} else {
		r1 = ret.Get(1).(domain.Category)
	}
	return r0, r1
}

// Classifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type Classifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - content string
func (_e *Classifier_Expecter) Classify(content interface{}) *Classifier_Classify_Call {
	return &Classifier_Classify_Call{Call: _e.mock.On("Classify", content)}
}

func (_c *Classifier_Classify_Call) Run(run func(content string)) *Classifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Classifier_Classify_Call) Return(categoryToFloat64 map[domain.Category]float64, category domain.Category) *Classifier_Classify_Call {
	_c.Call.Return(categoryToFloat64, category)
	return _c
}

func (_c *Classifier_Classify_Call) RunAndReturn(run func(content string) (map[domain.Category]float64, domain.Category)) *Classifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}
