// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"protomorphine/tg-notes/internal/app/models"
)

// NewNoteCreator creates a new instance of NoteCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteCreator {
	mock := &NoteCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NoteCreator is an autogenerated mock type for the NoteCreator type
type NoteCreator struct {
	mock.Mock
}

type NoteCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *NoteCreator) EXPECT() *NoteCreator_Expecter {
	return &NoteCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type NoteCreator
func (_mock *NoteCreator) Create(ctx context.Context, text string) (models.SaveResult, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.SaveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.SaveResult, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.SaveResult); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Get(0).(models.SaveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NoteCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NoteCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *NoteCreator_Expecter) Create(ctx interface{}, text interface{}) *NoteCreator_Create_Call {
	return &NoteCreator_Create_Call{Call: _e.mock.On("Create", ctx, text)}
}

func (_c *NoteCreator_Create_Call) Run(run func(ctx context.Context, text string)) *NoteCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NoteCreator_Create_Call) Return(saveResult models.SaveResult, err error) *NoteCreator_Create_Call {
	_c.Call.Return(saveResult, err)
	return _c
}

func (_c *NoteCreator_Create_Call) RunAndReturn(run func(ctx context.Context, text string) (models.SaveResult, error)) *NoteCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}
