// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"protomorphine/tg-notes/internal/app/models"
)

// NewNoteSaver creates a new instance of NoteSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteSaver {
	mock := &NoteSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NoteSaver is an autogenerated mock type for the NoteSaver type
type NoteSaver struct {
	mock.Mock
}

type NoteSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *NoteSaver) EXPECT() *NoteSaver_Expecter {
	return &NoteSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type NoteSaver
func (_mock *NoteSaver) Save(ctx context.Context, text string) (models.SaveResult, error) {
	ret := _mock.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 models.SaveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.SaveResult, error)); ok {
		return returnFunc(ctx, text)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.SaveResult); ok {
		r0 = returnFunc(ctx, text)
	} else {
		r0 = ret.Get(0).(models.SaveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NoteSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type NoteSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *NoteSaver_Expecter) Save(ctx interface{}, text interface{}) *NoteSaver_Save_Call {
	return &NoteSaver_Save_Call{Call: _e.mock.On("Save", ctx, text)}
}

func (_c *NoteSaver_Save_Call) Run(run func(ctx context.Context, text string)) *NoteSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *NoteSaver_Save_Call) Return(saveResult models.SaveResult, err error) *NoteSaver_Save_Call {
	_c.Call.Return(saveResult, err)
	return _c
}

func (_c *NoteSaver_Save_Call) RunAndReturn(run func(ctx context.Context, text string) (models.SaveResult, error)) *NoteSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
